### PR TITLE
Use java's createTempFile. Fixes #43

### LINKED ISSUE #43: SIGSEGV when running multiple instances
I have integrated Discord RPC functionality in my game using the jar file from the releases page (v1.6.2). It works just fine, but when I launch two instances of my game, the old instance crashes with a SIGSEGV. When I remove the Discord RPC related code, the game doesn't crash when launching multiple instances so it's something related to this.

This is basically what my code looks like:

```java
DiscordRPC.discordInitialize(applicationID, null, false);
richPresence = new DiscordRichPresence.Builder("")
        .setBigImage("logo", "v0.0.1")
        .setStartTimestamps(System.currentTimeMillis())
        .build();
richPresence.state = stateStr;
DiscordRPC.discordUpdatePresence(richPresence);
```

**Versions:**
 - OS: Linux
 - Java Version: `openjdk version "1.8.0_252"`
 - Library Version: `v1.6.2`

### PR DESCRIPTION
**Pull request by nickgal**
createTempFile generates a non-conflicting filename which avoids multiple processes trying to read/write the same file.

This fixes #43 the SIGSEGV when running multiple instances under linux.

### CODE REVIEW

File: src/main/java/net/arikia/dev/drpc/DiscordRPC.java [hunk 1]
```diff
@@ -125,38 +125,34 @@ public static void discordRespond(String userId, DiscordReply reply) {
...
+				copyFile(in, out);
+				f.deleteOnExit();
+			} catch (IOException e) {
+				e.printStackTrace();
+			}
 
-		System.load(f.getAbsolutePath());
+			System.load(f.getAbsolutePath());
+		} catch(Exception e) {
+				e.printStackTrace();
```
Comment (DeJayDev) [inline src/main/java/net/arikia/dev/drpc/DiscordRPC.java]: Remove a tab

**Review by DeJayDev — CHANGES_REQUESTED** [review]

**Comment by DeJayDev** [comment]
Love it, thanks for the PR. Small gripe with whatever happened on indentation on the reviewed line.

File: src/main/java/net/arikia/dev/drpc/DiscordRPC.java (hunk 1 above)
Comment (nickgal) [reply src/main/java/net/arikia/dev/drpc/DiscordRPC.java]: Not sure how that sneaked in.
